# Instructions

For the second part of the assignment tonight, we're going to get a little bit of practice with `Pandas`. We'll ask that you do a couple of different things using the new tools that we learned about (methods for combining data sets, `pd.cut`, and `pivot tables`).

# Assignment Questions

We'll be working with the `wine` datasets that are located in the `data` folder in this day's directory. 

1) Read the `winequality-red.csv` data into a `DataFrame`, and the `winequality-white.csv` into another `DataFrame`.

2) Double check that you've read them in right by using some of the attributes and methods available on `DataFrames` for getting a general sense of your data (**Hint**: See `day10-intro_pandas`, `week5` if you need a refresher on these). 

3) I've decided that this month I want to stay away from wines with relatively high alcohol content. To do that, I'm going to avoid any wines that have a greater alcohol content than the mean alcohol content, and you're going to help me do this. To achieve this, let's do the following: 

  * Find the mean alcohol content, separately, for reds and whites.  
  * Create a `Series` that holds whether each row in each `DataFrame` (the reds, and whites) has a higher alcohol content than the mean. 
  * Merge this `Series` onto the `DataFrame`. I can imagine doing this with either a `.join()` or using `pd.concat()`. For practice, do it with both. Note: merges with `Series` work the same way that they work with `DataFrames`.  
  * Return back to me all those rows that will help me stay away from those wines with a higher alcohol content.  
   
   
4) Let's say that I want to get started on cutting back next month. This time, though, I want to focus on staying away from those wines with a high acidity. Specifically, I want to stay away from those wines that are in the highest bin of fixed acidity (highest bin out of 5). You're now going to help me do this. To achieve this, let's do the following: 

 * Separate the rows in each `DataFrame` into 5 equal width bins based off their fixed acidity. 
 * Merge the resulting `Series` holding these 5 bins onto the original `DataFrame`. I can imagine also doing this with either `.join()` or using `pd.concat()`. Try doing it with both for practice. 
 * Return back to me all those rows that are **not in ** the top bin in terms of fixed acidity. 

5) Let's say that I now want to know how much my decision to avoid those wines with higher `alcohol` content is going to limit the `quality` of wines that I can drink. To figure this out, I want to know a couple of things: 

 * The average `alcohol` content for those reds above the mean `alcohol` level, by quality.
 * The average `alcohol` content for those whites above the mean `alcohol` level, by quality. 
 
 Use a `pivot table` to solve this. 
 
6) Now, do the same for my decision to avoid wines with a high acidity next month: 

 * Find the average `alcohol` content for reds, by `quality` and `fixed acidity` quintile. 
 * Find the average `alcohol` content for whites, by `quality` and `fixed acidity` quintile. 
 
  Use a `pivot table` to solve this.

In [5]:
#1
import pandas as pd
red_df =pd.read_csv('data/winequality-red.csv', delimiter=';')
white_df =pd.read_csv('data/winequality-white.csv', delimiter=';')

In [3]:
#2
red_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
white_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [8]:
red_df.shape

(1599, 12)

In [9]:
white_df.shape

(4898, 12)

In [17]:
#3
red_mean_acc=red_df['alcohol'].mean()
print(red_mean_acc)

10.422983114446502

In [14]:
white_mean_acc=white_df['alcohol'].mean()
print(white_mean_acc)

10.514267047774638

In [20]:
import numpy as np
red_df['acc_mean_check']=np.where(red_df['alcohol']>red_mean_acc,'Yes','No')
red_df.head()
white_df['acc_mean_check']=np.where(white_df['alcohol']>white_mean_acc,'Yes','No')
white_df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,acc_mean_check
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,No
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,No
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,No
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,No
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,No

In [24]:
wine_can_drink=red_df[red_df['acc_mean_check']=='No'].append(white_df[white_df['acc_mean_check']=='No'])
wine_can_drink.head(10)
wine_can_drink.shape

(3651, 13)

In [56]:
#4
red_bin=pd.cut(red_df['fixed acidity'], bins=5,labels=[1,2,3,4,5])
red_bin.name='cat'
new_red=[red_bin,red_df]
red_acid=pd.concat(new_red,axis=1)
red_acid.shape
print(red_acid)

0       2
1       2
2       2
3       3
4       2
5       2
6       2
7       2
8       2
9       2
10      1
11      2
12      1
13      2
14      2
15      2
16      2
17      2
18      2
19      2
20      2
21      2
22      2
23      2
24      2
25      1
26      2
27      2
28      2
29      2
       ..
1569    1
1570    1
1571    1
1572    2
1573    1
1574    1
1575    2
1576    2
1577    1
1578    1
1579    1
1580    2
1581    1
1582    1
1583    1
1584    1
1585    2
1586    2
1587    1
1588    2
1589    1
1590    1
1591    1
1592    1
1593    1
1594    1
1595    1
1596    1
1597    1
1598    1
Name: cat, Length: 1599, dtype: category
Categories (5, int64): [1 < 2 < 3 < 4 < 5]

In [50]:
white_bin=pd.cut(white_df['fixed acidity'], bins=5,labels=[1,2,3,4,5])
white_bin.name='cat'
new_white=[white_bin,white_df]
white_acid=pd.concat(new_white,axis=1)
white_acid.shape
print(white_acid.shape)
print(white_acid)

(4898, 14)
     cat  fixed acidity  volatile acidity  citric acid  residual sugar  \
0      2            7.0             0.270         0.36           20.70
1      2            6.3             0.300         0.34            1.60
2      3            8.1             0.280         0.40            6.90
3      2            7.2             0.230         0.32            8.50
4      2            7.2             0.230         0.32            8.50
5      3            8.1             0.280         0.40            6.90
6      2            6.2             0.320         0.16            7.00
7      2            7.0             0.270         0.36           20.70
8      2            6.3             0.300         0.34            1.60
9      3            8.1             0.220         0.43            1.50
10     3            8.1             0.270         0.41            1.45
11     3            8.6             0.230         0.40            4.20
12     2            7.9             0.180         0.37            1.20
13     2            6.6             0.160         0.40            1.50
14     3            8.3             0.420         0.62           19.25
15     2            6.6             0.170         0.38            1.50
16     2            6.3             0.480         0.04            1.10
17     2            6.2             0.660         0.48            1.20
18     2            7.4             0.340         0.42            1.10
19     2            6.5             0.310         0.14            7.50
20     2            6.2             0.660         0.48            1.20
21     2            6.4             0.310         0.38            2.90
22     2            6.8             0.260         0.42            1.70
23     2            7.6             0.670         0.14            1.50
24     2            6.6             0.270         0.41            1.30
25     2            7.0             0.250         0.32            9.00
26     2            6.9             0.240         0.35            1.00
27     2            7.0             0.280         0.39            8.70
28     2            7.4             0.270         0.48            1.10
29     2            7.2             0.320         0.36            2.00
...   ..            ...               ...          ...             ...
4868   1            5.8             0.230         0.31            4.50
4869   2            6.6             0.240         0.33           10.10
4870   2            6.1             0.320         0.28            6.60
4871   1            5.0             0.200         0.40            1.90
4872   2            6.0             0.420         0.41           12.40
4873   1            5.7             0.210         0.32            1.60
4874   1            5.6             0.200         0.36            2.50
4875   2            7.4             0.220         0.26            1.20
4876   2            6.2             0.380         0.42            2.50
4877   2            5.9             0.540         0.00            0.80
4878   2            6.2             0.530         0.02            0.90
4879   2            6.6             0.340         0.40            8.10
4880   2            6.6             0.340         0.40            8.10
4881   1            5.0             0.235         0.27           11.75
4882   1            5.5             0.320         0.13            1.30
4883   1            4.9             0.470         0.17            1.90
4884   2            6.5             0.330         0.38            8.30
4885   2            6.6             0.340         0.40            8.10
4886   2            6.2             0.210         0.28            5.70
4887   2            6.2             0.410         0.22            1.90
4888   2            6.8             0.220         0.36            1.20
4889   1            4.9             0.235         0.27           11.75
4890   2            6.1             0.340         0.29            2.20
4891   1            5.7             0.210         0.32            0.90
4892   2            6.5             0.230         0.38            1.30
4893   2            6.2             0.210         0.29            1.60
4894   2            6.6             0.320         0.36            8.00
4895   2            6.5             0.240         0.19            1.20
4896   1            5.5             0.290         0.30            1.10
4897   2            6.0             0.210         0.38            0.80

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00
1         0.049                 14.0                 132.0  0.99400  3.30
2         0.050                 30.0                  97.0  0.99510  3.26
3         0.058                 47.0                 186.0  0.99560  3.19
4         0.058                 47.0                 186.0  0.99560  3.19
5         0.050                 30.0                  97.0  0.99510  3.26
6         0.045                 30.0                 136.0  0.99490  3.18
7         0.045                 45.0                 170.0  1.00100  3.00
8         0.049                 14.0                 132.0  0.99400  3.30
9         0.044                 28.0                 129.0  0.99380  3.22
10        0.033                 11.0                  63.0  0.99080  2.99
11        0.035                 17.0                 109.0  0.99470  3.14
12        0.040                 16.0                  75.0  0.99200  3.18
13        0.044                 48.0                 143.0  0.99120  3.54
14        0.040                 41.0                 172.0  1.00020  2.98
15        0.032                 28.0                 112.0  0.99140  3.25
16        0.046                 30.0                  99.0  0.99280  3.24
17        0.029                 29.0                  75.0  0.98920  3.33
18        0.033                 17.0                 171.0  0.99170  3.12
19        0.044                 34.0                 133.0  0.99550  3.22
20        0.029                 29.0                  75.0  0.98920  3.33
21        0.038                 19.0                 102.0  0.99120  3.17
22        0.049                 41.0                 122.0  0.99300  3.47
23        0.074                 25.0                 168.0  0.99370  3.05
24        0.052                 16.0                 142.0  0.99510  3.42
25        0.046                 56.0                 245.0  0.99550  3.25
26        0.052                 35.0                 146.0  0.99300  3.45
27        0.051                 32.0                 141.0  0.99610  3.38
28        0.047                 17.0                 132.0  0.99140  3.19
29        0.033                 37.0                 114.0  0.99060  3.10
...         ...                  ...                   ...      ...   ...
4868      0.046                 42.0                 124.0  0.99324  3.31
4869      0.032                  8.0                  81.0  0.99626  3.19
4870      0.021                 29.0                 132.0  0.99188  3.15
4871      0.015                 20.0                  98.0  0.98970  3.37
4872      0.032                 50.0                 179.0  0.99622  3.14
4873      0.030                 33.0                 122.0  0.99044  3.33
4874      0.048                 16.0                 125.0  0.99282  3.49
4875      0.035                 18.0                  97.0  0.99245  3.12
4876      0.038                 34.0                 117.0  0.99132  3.36
4877      0.032                 12.0                  82.0  0.99286  3.25
4878      0.035                  6.0                  81.0  0.99234  3.24
4879      0.046                 68.0                 170.0  0.99494  3.15
4880      0.046                 68.0                 170.0  0.99494  3.15
4881      0.030                 34.0                 118.0  0.99540  3.07
4882      0.037                 45.0                 156.0  0.99184  3.26
4883      0.035                 60.0                 148.0  0.98964  3.27
4884      0.048                 68.0                 174.0  0.99492  3.14
4885      0.046                 68.0                 170.0  0.99494  3.15
4886      0.028                 45.0                 121.0  0.99168  3.21
4887      0.023                  5.0                  56.0  0.98928  3.04
4888      0.052                 38.0                 127.0  0.99330  3.04
4889      0.030                 34.0                 118.0  0.99540  3.07
4890      0.036                 25.0                 100.0  0.98938  3.06
4891      0.038                 38.0                 121.0  0.99074  3.24
4892      0.032                 29.0                 112.0  0.99298  3.29
4893      0.039                 24.0                  92.0  0.99114  3.27
4894      0.047                 57.0                 168.0  0.99490  3.15
4895      0.041                 30.0                 111.0  0.99254  2.99
4896      0.022                 20.0                 110.0  0.98869  3.34
4897      0.020                 22.0                  98.0  0.98941  3.26

      sulphates    alcohol  quality acc_mean_check
0          0.45   8.800000        6             No
1          0.49   9.500000        6             No
2          0.44  10.100000        6             No
3          0.40   9.900000        6             No
4          0.40   9.900000        6             No
5          0.44  10.100000        6             No
6          0.47   9.600000        6             No
7          0.45   8.800000        6             No
8          0.49   9.500000        6             No
9          0.45  11.000000        6            Yes
10         0.56  12.000000        5            Yes
11         0.53   9.700000        5             No
12         0.63  10.800000        5            Yes
13         0.52  12.400000        7            Yes
14         0.67   9.700000        5             No
15         0.55  11.400000        7            Yes
16         0.36   9.600000        6             No
17         0.39  12.800000        8            Yes
18         0.53  11.300000        6            Yes
19         0.50   9.500000        5             No
20         0.39  12.800000        8            Yes
21         0.35  11.000000        7            Yes
22         0.48  10.500000        8             No
23         0.51   9.300000        5             No
24         0.47  10.000000        6             No
25         0.50  10.400000        6             No
26         0.44  10.000000        6             No
27         0.53  10.500000        6             No
28         0.49  11.600000        6            Yes
29         0.71  12.300000        7            Yes
...         ...        ...      ...            ...
4868       0.64  10.800000        6            Yes
4869       0.51   9.800000        6             No
4870       0.36  11.450000        7            Yes
4871       0.55  12.050000        6            Yes
4872       0.60   9.700000        5             No
4873       0.52  11.900000        6            Yes
4874       0.49  10.000000        6             No
4875       0.41   9.700000        6             No
4876       0.59  11.600000        7            Yes
4877       0.36   8.800000        5             No
4878       0.35   9.500000        4             No
4879       0.50   9.533333        6             No
4880       0.50   9.533333        6             No
4881       0.50   9.400000        6             No
4882       0.38  10.700000        5            Yes
4883       0.35  11.500000        6            Yes
4884       0.50   9.600000        5             No
4885       0.50   9.550000        6             No
4886       1.08  12.150000        7            Yes
4887       0.79  13.000000        7            Yes
4888       0.54   9.200000        5             No
4889       0.50   9.400000        6             No
4890       0.44  11.800000        6            Yes
4891       0.46  10.600000        6            Yes
4892       0.54   9.700000        5             No
4893       0.50  11.200000        6            Yes
4894       0.46   9.600000        5             No
4895       0.46   9.400000        6             No
4896       0.38  12.800000        7            Yes
4897       0.32  11.800000        6            Yes

[4898 rows x 14 columns]

In [58]:
red_acid[red_acid['cat']<4]
white_acid[white_acid['cat']<4]

,cat,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,acc_mean_check
0,2,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.800000,6,No
1,2,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.500000,6,No
2,3,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.100000,6,No
3,2,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.900000,6,No
4,2,7.2,0.230,0.32,8.50,0.058,47.0,186.0,0.99560,3.19,0.40,9.900000,6,No
5,3,8.1,0.280,0.40,6.90,0.050,30.0,97.0,0.99510,3.26,0.44,10.100000,6,No
6,2,6.2,0.320,0.16,7.00,0.045,30.0,136.0,0.99490,3.18,0.47,9.600000,6,No
7,2,7.0,0.270,0.36,20.70,0.045,45.0,170.0,1.00100,3.00,0.45,8.800000,6,No
8,2,6.3,0.300,0.34,1.60,0.049,14.0,132.0,0.99400,3.30,0.49,9.500000,6,No
9,3,8.1,0.220,0.43,1.50,0.044,28.0,129.0,0.99380,3.22,0.45,11.000000,6,Yes
10,3,8.1,0.270,0.41,1.45,0.033,11.0,63.0,0.99080,2.99,0.56,12.000000,5,Yes
11,3,8.6,0.230,0.40,4.20,0.035,17.0,109.0,0.99470,3.14,0.53,9.700000,5,No
12,2,7.9,0.180,0.37,1.20,0.040,16.0,75.0,0.99200,3.18,0.63,10.800000,5,Yes
13,2,6.6,0.160,0.40,1.50,0.044,48.0,143.0,0.99120,3.54,0.52,12.400000,7,Yes
14,3,8.3,0.420,0.62,19.25,0.040,41.0,172.0,1.00020,2.98,0.67,9.700000,5,No
15,2,6.6,0.170,0.38,1.50,0.032,28.0,112.0,0.99140,3.25,0.55,11.400000,7,Yes
16,2,6.3,0.480,0.04,1.10,0.046,30.0,99.0,0.99280,3.24,0.36,9.600000,6,No
17,2,6.2,0.660,0.48,1.20,0.029,29.0,75.0,0.98920,3.33,0.39,12.800000,8,Yes
18,2,7.4,0.340,0.42,1.10,0.033,17.0,171.0,0.99170,3.12,0.53,11.300000,6,Yes
19,2,6.5,0.310,0.14,7.50,0.044,34.0,133.0,0.99550,3.22,0.50,9.500000,5,No
20,2,6.2,0.660,0.48,1.20,0.029,29.0,75.0,0.98920,3.33,0.39,12.800000,8,Yes
21,2,6.4,0.310,0.38,2.90,0.038,19.0,102.0,0.99120,3.17,0.35,11.000000,7,Yes
22,2,6.8,0.260,0.42,1.70,0.049,41.0,122.0,0.99300,3.47,0.48,10.500000,8,No
23,2,7.6,0.670,0.14,1.50,0.074,25.0,168.0,0.99370,3.05,0.51,9.300000,5,No
24,2,6.6,0.270,0.41,1.30,0.052,16.0,142.0,0.99510,3.42,0.47,10.000000,6,No
25,2,7.0,0.250,0.32,9.00,0.046,56.0,245.0,0.99550,3.25,0.50,10.400000,6,No
26,2,6.9,0.240,0.35,1.00,0.052,35.0,146.0,0.99300,3.45,0.44,10.000000,6,No
27,2,7.0,0.280,0.39,8.70,0.051,32.0,141.0,0.99610,3.38,0.53,10.500000,6,No
28,2,7.4,0.270,0.48,1.10,0.047,17.0,132.0,0.99140,3.19,0.49,11.600000,6,Yes
29,2,7.2,0.320,0.36,2.00,0.033,37.0,114.0,0.99060,3.10,0.71,12.300000,7,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4868,1,5.8,0.230,0.31,4.50,0.046,42.0,124.0,0.99324,3.31,0.64,10.800000,6,Yes
4869,2,6.6,0.240,0.33,10.10,0.032,8.0,81.0,0.99626,3.19,0.51,9.800000,6,No
4870,2,6.1,0.320,0.28,6.60,0.021,29.0,132.0,0.99188,3.15,0.36,11.450000,7,Yes
4871,1,5.0,0.200,0.40,1.90,0.015,20.0,98.0,0.98970,3.37,0.55,12.050000,6,Yes
4872,2,6.0,0.420,0.41,12.40,0.032,50.0,179.0,0.99622,3.14,0.60,9.700000,5,No
4873,1,5.7,0.210,0.32,1.60,0.030,33.0,122.0,0.99044,3.33,0.52,11.900000,6,Yes
4874,1,5.6,0.200,0.36,2.50,0.048,16.0,125.0,0.99282,3.49,0.49,10.000000,6,No
4875,2,7.4,0.220,0.26,1.20,0.035,18.0,97.0,0.99245,3.12,0.41,9.700000,6,No
4876,2,6.2,0.380,0.42,2.50,0.038,34.0,117.0,0.99132,3.36,0.59,11.600000,7,Yes
4877,2,5.9,0.540,0.00,0.80,0.032,12.0,82.0,0.99286,3.25,0.36,8.800000,5,No
4878,2,6.2,0.530,0.02,0.90,0.035,6.0,81.0,0.99234,3.24,0.35,9.500000,4,No
4879,2,6.6,0.340,0.40,8.10,0.046,68.0,170.0,0.99494,3.15,0.50,9.533333,6,No
4880,2,6.6,0.340,0.40,8.10,0.046,68.0,170.0,0.99494,3.15,0.50,9.533333,6,No
4881,1,5.0,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.400000,6,No
4882,1,5.5,0.320,0.13,1.30,0.037,45.0,156.0,0.99184,3.26,0.38,10.700000,5,Yes
4883,1,4.9,0.470,0.17,1.90,0.035,60.0,148.0,0.98964,3.27,0.35,11.500000,6,Yes
4884,2,6.5,0.330,0.38,8.30,0.048,68.0,174.0,0.99492,3.14,0.50,9.600000,5,No
4885,2,6.6,0.340,0.40,8.10,0.046,68.0,170.0,0.99494,3.15,0.50,9.550000,6,No
4886,2,6.2,0.210,0.28,5.70,0.028,45.0,121.0,0.99168,3.21,1.08,12.150000,7,Yes
4887,2,6.2,0.410,0.22,1.90,0.023,5.0,56.0,0.98928,3.04,0.79,13.000000,7,Yes
4888,2,6.8,0.220,0.36,1.20,0.052,38.0,127.0,0.99330,3.04,0.54,9.200000,5,No
4889,1,4.9,0.235,0.27,11.75,0.030,34.0,118.0,0.99540,3.07,0.50,9.400000,6,No
4890,2,6.1,0.340,0.29,2.20,0.036,25.0,100.0,0.98938,3.06,0.44,11.800000,6,Yes
4891,1,5.7,0.210,0.32,0.90,0.038,38.0,121.0,0.99074,3.24,0.46,10.600000,6,Yes
4892,2,6.5,0.230,0.38,1.30,0.032,29.0,112.0,0.99298,3.29,0.54,9.700000,5,No
4893,2,6.2,0.210,0.29,1.60,0.039,24.0,92.0,0.99114,3.27,0.50,11.200000,6,Yes
4894,2,6.6,0.320,0.36,8.00,0.047,57.0,168.0,0.99490,3.15,0.46,9.600000,5,No
4895,2,6.5,0.240,0.19,1.20,0.041,30.0,111.0,0.99254,2.99,0.46,9.400000,6,No
4896,1,5.5,0.290,0.30,1.10,0.022,20.0,110.0,0.98869,3.34,0.38,12.800000,7,Yes
4897,2,6.0,0.210,0.38,0.80,0.020,22.0,98.0,0.98941,3.26,0.32,11.800000,6,Yes

In [64]:
#5
pd.pivot_table(red_df, values='alcohol', index='quality', columns='acc_mean_check',aggfunc=np.mean)

acc_mean_check        No        Yes
quality
3               9.564286  10.866667
4               9.640909  11.295000
5               9.600276  11.088686
6               9.736524  11.437214
7               9.922222  11.708236
8               9.900000  12.368750

In [65]:
pd.pivot_table(white_df, values='alcohol', index='quality', columns='acc_mean_check')

acc_mean_check         No        Yes
quality
3                9.558333  11.525000
4                9.636638  11.425532
5                9.481132  11.211099
6                9.679489  11.604366
7                9.666667  11.924761
8                9.469697  12.139437
9               10.400000  12.625000

In [68]:
#6
pd.pivot_table(red_acid, values='alcohol', index='quality', columns='cat')

cat              1          2          3          4          5
quality
3         9.875000  10.500000   9.150000   9.000000        NaN
4        11.006667   9.981667   9.920000   9.966667        NaN
5        10.304245   9.773727   9.846429  10.229630  12.050000
6        11.223529  10.431985  10.687395  10.480952  10.240000
7        12.195402  11.486413  11.383333  10.809524   9.866667
8        13.633333  11.937500  11.916667   9.800000        NaN

In [69]:
pd.pivot_table(white_acid, values='alcohol', index='quality', columns='cat')

cat              1          2          3     4     5
quality
3         9.850000  10.472727  10.540000  9.65   NaN
4        10.786364  10.102564  10.126471  9.90   NaN
5        10.136635   9.732173  10.176452  9.70   NaN
6        10.902765  10.529056  10.635247  9.50  11.1
7        12.021405  11.303724  10.988679   NaN   NaN
8        12.403030  11.486364  11.080000   NaN   NaN
9              NaN  12.625000  10.400000   NaN   NaN